### ISSUE TITLE
支持 F11 全屏吗？

### ISSUE THREAD

**Issue by veryyoung** [ksky521/nodePPT#105]
我试了下几个 demo，貌似都不支持呢。

浏览器的状态栏啥的看着挺影响美观的。

**Comment by tindytian** [comment]
确实要是能够支持全屏就好了。

**Comment by veryyoung** [comment]
@tindytian 我在 local 跑就支持全屏

**Comment by ksky521** [comment]
刚开始是windows自己就支持，后来换了mac发现不行，所以 *新版本1.4.0* 会支持！

**Comment by ksky521** [comment]
1.4.0已经支持！
