### ISSUE TITLE
nodeppt安装失败

### ISSUE THREAD

**Issue by roothoo** [ksky521/nodePPT#110]
sudo npm install  nodeppt                                                    15-11-29 19:07
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "nodeppt"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! shasum check failed for /tmp/npm-10462-b59dbe93/registry.npmjs.org/mathjax/-/mathjax-2.5.1.tgz
npm ERR! Expected: 7e9dde72faff8f7248e1d480a6971b4019a61890
npm ERR! Actual:   88aae7e5ddd582fc0861a9343f53cf82801fb82f
npm ERR! From:     http://registry.npmjs.org/mathjax/-/mathjax-2.5.1.tgz
npm ERR! 

使用taobao镜像也不行，https://registry.npm.taobao.org

**Comment by roothoo** [comment]
可能是mathjax有问题，单独安装mathjax也不行
sudo npm install http://registry.npmjs.org/mathjax/-/mathjax-2.5.1.tgz       15-11-29 19:09
npm ERR! tar.unpack untar error /tmp/npm-10537-b8613b9c/registry.npmjs.org/mathjax/-/mathjax-2.5.1.tgz
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "http://registry.npmjs.org/mathjax/-/mathjax-2.5.1.tgz"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! invalid tar file

**Comment by ksky521** [comment]
在安装下试试，我刚才试了没问题~
