### ISSUE TITLE
nodeppt generate ./ppts/demo.md -a生成的publish文件夹好大

### ISSUE THREAD

**Issue by fumanduo2** [ksky521/nodePPT#111]
nodeppt generate ./ppts/demo.md -a 生成的publish文件夹好大，发现js就有100多M，而实际用到的不会这么大吧，请问怎么解决？

**Comment by ksky521** [comment]
这个主要是demo用到了mathjax，他的内容太大~ 一般用不到不要选择

**Comment by fumanduo2** [comment]
一般用不到不要选择 这个怎么操作。

**Comment by ksky521** [comment]
不用选择，默认就没有~

**Comment by fumanduo2** [comment]
哦哦。
