### ISSUE TITLE
主题和分栏布局

### ISSUE THREAD

**Issue by benjamin-zuo** [ksky521/nodePPT#113]
今天用了下，有两个小Tip:
1. Dark theme 的代码块背景色搞成白色就好看多了，黑色不太清晰
2. 还有个就是多栏布局的问题，现在我直接指定类，内嵌的<style></style>

**Comment by ksky521** [comment]
1.可以指定highlightjs的主题
2.多栏布局使用columns-x，目前还没想到好的简写方式。。
