### ISSUE TITLE
安装完成，运行出错

### ISSUE THREAD

**Issue by JianbinDong** [ksky521/nodeppt#117]
利用npm安装，安装完成后在/use/local/bin/里面生产nodeppt，以及在/user/local/lob里面生产了module，nodeppt文件里的内容和github的工程一样是#!/usr/bin/env node，但是运行的时候/usr/bin/env: node: 没有那个文件或目录包这个错误。。。为什么？

**Comment by WeiLiuCs** [comment]
我从网上找到了一个解决方法：

sudo apt-get install nodejs-legacy

**Comment by ksky521** [comment]
欢迎使用2.0版本
