### ISSUE TITLE
导出 pdf 功能无法正常使用

### ISSUE THREAD

**Issue by defcc** [ksky521/nodePPT#120]
![image](https://cloud.githubusercontent.com/assets/2603918/13099696/cb591bfc-d56f-11e5-818b-e8a6ffaab505.png)

见图，是空白的

浏览器：mac chrome 版本 48.0.2564.109 (64-bit)

**Comment by ksky521** [comment]
把#改到100以上（超过页数），然后就应该ok了，具体原因还没找到。。。
