### ISSUE TITLE
在centos上找不到作为后台进程永远运行的办法

### ISSUE THREAD

**Issue by artbite007** [ksky521/nodePPT#129]
我是部署在远程centos服务器上
1，打开SSH终端，使用nodeppt start命令启动后，一旦关闭终端，程序马上变得不可访问
2，在远程服务器上安装了forever, 使用forever nodeppt star，依然不能做到让进程成为永远运行的后台进程

**Comment by artbite007** [comment]
先谢了！

**Comment by zl810881283** [comment]
使用pm2之类的软件管理进程即可，可以参看我的对nodePPT的[改进版本](https://github.com/zl810881283/ppt)，将其clone到你的服务器上。
```shell
npm start
```
即可
