### ISSUE TITLE
本地图片以及mathjax的js好像没有加载

### ISSUE THREAD

**Issue by specter119** [ksky521/nodePPT#131]
OS version: OSX 10.11.5
npm version: 3.9.5

## 状况

Latex公式不显示，本地图片不显示。
右键打开图片网页提示：
```
This request URL md/figs/pf_mu_YCuSe2_600K.svg was not found on this server.
```

用`nodeppt start -d path`启动后，打开的网址为`172.31.98.78:8080`，断网或者强制host可以打开`127.0.0.1:8080`，但是图片和Latex依旧无法渲染，在markdown里面图片、Latex渲染正常。

## 安装过程

```
brew install npm
npm install -g nodeppt
```

npm需要设置环境变量吗？新手不懂的。

## Update

折腾了几遍npm，现在已经是不断网就打不开nodePPT了。

**Comment by ksky521** [comment]
试了下npm 3.10.2版本，没有问题，你升级下npm试下

**Comment by specter119** [comment]
@ksky521 好的，我试试，之前的node版本是6.2.1比较正常，现在是6.2.2，然后我临时的解决方案是，找个不常用的浏览器，代理设为本地，可以打开。

**Comment by ksky521** [comment]
看样子更像是你写的图片路径不对，你写/xxx/xxx试试

**Comment by specter119** [comment]
@ksky521 谢谢，现在图片显示了，latex依旧不显示，已经`usemathjax: yes`了。不过现在的大问题是，不能正常打开了，需要浏览器断网才行。我自己这边先弄好了，有需要继续反馈。非常感谢热心帮助，我自己关了。
