### ISSUE TITLE
$\Lambda$ 渲染不出来

### ISSUE THREAD

**Issue by specter119** [ksky521/nodeppt#132]
在别的基于MathJax的工具上，渲染正常，加入$\Lambda$ ，整个公式就有可能渲染不出来。
请测试：

$\Lambda$

$$\sum_\Lambda e^{ik\cdot R} $$

$$\sum e^{ik\cdot R} $$

$$\sum e^{ik\cdot\Lambda R} $$

**Comment by libchaos** [comment]
我测试时行内公式$\lambda$不行，块级$$\lambda$$的可以

**Comment by ksky521** [comment]
欢迎使用2.0版本
