### ISSUE TITLE
对于图片路径的疑问

### ISSUE THREAD

**Issue by specter119** [ksky521/nodeppt#133]
首先声明，我对html一点也不懂，就是以一个非常外行的人提一些建议~

为什么图片的路径不能写那种通常的相对路径，还要在相对路径前面加`\`？如果可以支持通常的相对路径，那么除了特效和主题以外，所有的内容在markdown里面都可以预览。然后打开nodePPT再去看效果，毕竟编辑的时候，都是在Markdown里面去编辑的啊~

所以，如果可能的话，能否考虑支持不加`\`的普通图片路径？谢谢您为开发nodePPT努力，现在这个已经是一个足够好的工具了。

**Comment by ksky521** [comment]
欢迎使用2.0版本
