### ISSUE TITLE
导出 html 时指定 lib 路径

### ISSUE THREAD

**Issue by HakurouKen** [ksky521/nodePPT#142]
在导出 html 文件的时候，html 中所有 css/js 文件引用都指向导出目录 `./` ，在多个 presentation 并存时，不好管理文件目录，尤其是多个 presentation 中，混合采用 nodeppt 和其它工具(例如 reveal.js / remark.js) 生成 html 文件的时候。例如我期望的项目路径是：

```
.
├── lib
│   ├── nodeppt
│   ├── remarkjs
│   └── revealjs
├── publish
│   ├── another-presentation-nodeppt.html
│   ├── presentation-nodeppt.html
│   ├── presentation-remarkjs.html
│   └── presentation-revealjs.html
└── src
    ├── another-presentation-nodeppt
    │   └── presentation.md
    ├── presentation-nodeppt
    │   └── ppt.md
    └── presentation-remarkjs
        └── remarkjs.md
```

这种情况下，需要手动修改生成的 html 代码中 css/js 的引用路径。能否在导出的时候添加一个参数指定这个相对路径？例如在上述目录中，假设当前路径为 `src/presentation-nodeppt/`, 执行 `nodeppt generate ppt -o ../../publish -p ../lib/nodeppt`

**Comment by congzhaoyang** [comment]
请问你的可以build出HTML文件吗？我的执行`nodeppt build slide.md`就报`Entry file slide.md does not exist.`，但这个文件是存在的
