### ISSUE TITLE
安装失败 node版本6.2.0 npm版本3.8.9

### ISSUE THREAD

**Issue by jcto** [ksky521/nodePPT#144]
安装失败：
 npm install -g nodeppt
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "nodeppt"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! shasum check failed for C:\Users\opg\AppData\Local\Temp\npm-6456-2041f55a\registry.npmjs.org\mathjax-\mathjax-2.6.1.tgz
npm ERR! Expected: bdb1b2f34ee0423825260eab25260dfda99613bb
npm ERR! Actual:   21e9cf87e96197b616507e18394f85f02eda5482
npm ERR! From:     https://registry.npmjs.org/mathjax/-/mathjax-2.6.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\npm-debug.log

**Comment by mingzhangyong** [comment]
sudo 再次运行看看

**Comment by ksky521** [comment]
mac使用了6.10.0+npm4.5没有问题
