### ISSUE TITLE
ubuntu下nodeppt start失败

### ISSUE THREAD

**Issue by koybe** [ksky521/nodeppt#154]
环境：ubuntu16.04 lts，node v7.4.0，npm 4.0.5
以下是安装输出
➜  ~ npm install -g nodeppt
/home/koybechan/.nvm/versions/node/v7.4.0/bin/nodeppt -> /home/koybechan/.nvm/versions/node/v7.4.0/lib/node_modules/nodeppt/bin/nodeppt

> ws@0.4.31 install /home/koybechan/.nvm/versions/node/v7.4.0/lib/node_modules/nodeppt/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/koybechan/.nvm/versions/node/v7.4.0/lib/node_modules/nodeppt/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:96: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/home/koybechan/.nvm/versions/node/v7.4.0/lib/node_modules/nodeppt/node_modules/engine.io-client/node_modules/ws/build'

> ws@0.5.0 install /home/koybechan/.nvm/versions/node/v7.4.0/lib/node_modules/nodeppt/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/koybechan/.nvm/versions/node/v7.4.0/lib/node_modules/nodeppt/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:96: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/home/koybechan/.nvm/versions/node/v7.4.0/lib/node_modules/nodeppt/node_modules/ws/build'
/home/koybechan/.nvm/versions/node/v7.4.0/lib
└─┬ nodeppt@1.4.2 
  ├─┬ chokidar@1.6.1
  │ ├─┬ anymatch@1.3.0 
  │ │ ├── arrify@1.0.1 
  │ │ └─┬ micromatch@2.3.11 
  │ │   ├─┬ arr-diff@2.0.0 
  │ │   │ └── arr-flatten@1.0.1 
  │ │   ├── array-unique@0.2.1 
  │ │   ├─┬ braces@1.8.5 
  │ │   │ ├─┬ expand-range@1.8.2 
  │ │   │ │ └─┬ fill-range@2.2.3 
  │ │   │ │   ├── is-number@2.1.0 
  │ │   │ │   ├── isobject@2.1.0 
  │ │   │ │   ├── randomatic@1.1.6 
  │ │   │ │   └── repeat-string@1.6.1 
  │ │   │ ├── preserve@0.2.0 
  │ │   │ └── repeat-element@1.1.2 
  │ │   ├─┬ expand-brackets@0.1.5 
  │ │   │ └── is-posix-bracket@0.1.1 
  │ │   ├── extglob@0.3.2 
  │ │   ├── filename-regex@2.0.0 
  │ │   ├─┬ kind-of@3.1.0 
  │ │   │ └── is-buffer@1.1.4 
  │ │   ├── normalize-path@2.0.1 
  │ │   ├─┬ object.omit@2.0.1 
  │ │   │ ├─┬ for-own@0.1.4 
  │ │   │ │ └── for-in@0.1.6 
  │ │   │ └── is-extendable@0.1.1 
  │ │   ├─┬ parse-glob@3.0.4 
  │ │   │ ├── glob-base@0.3.0 
  │ │   │ └── is-dotfile@1.0.2 
  │ │   └─┬ regex-cache@0.4.3 
  │ │     ├── is-equal-shallow@0.1.3 
  │ │     └── is-primitive@2.0.0 
  │ ├── async-each@1.0.1 
  │ ├── glob-parent@2.0.0 
  │ ├── inherits@2.0.3 
  │ ├─┬ is-binary-path@1.0.1 
  │ │ └── binary-extensions@1.8.0 
  │ ├─┬ is-glob@2.0.1 
  │ │ └── is-extglob@1.0.0 
  │ ├── path-is-absolute@1.0.1 
  │ └─┬ readdirp@2.1.0 
  │   ├── graceful-fs@4.1.11 
  │   ├─┬ minimatch@3.0.3 
  │   │ └─┬ brace-expansion@1.1.6 
  │   │   ├── balanced-match@0.4.2 
  │   │   └── concat-map@0.0.1 
  │   ├─┬ readable-stream@2.2.2 
  │   │ ├── buffer-shims@1.0.0 
  │   │ ├── core-util-is@1.0.2 
  │   │ ├── isarray@1.0.0 
  │   │ ├── process-nextick-args@1.0.7 
  │   │ ├── string_decoder@0.10.31 
  │   │ └── util-deprecate@1.0.2 
  │   └── set-immediate-shim@1.0.1 
  ├─┬ commander@2.9.0
  │ └── graceful-readlink@1.0.1 
  ├─┬ connect@2.11.0
  │ ├── buffer-crc32@0.2.1 
  │ ├── bytes@0.2.1 
  │ ├── cookie-signature@1.0.1 
  │ ├── fresh@0.2.0 
  │ ├── methods@0.0.1 
  │ ├─┬ multiparty@2.2.0 
  │ │ ├─┬ readable-stream@1.1.14 
  │ │ │ └── isarray@0.0.1 
  │ │ └─┬ stream-counter@0.2.0 
  │ │   └─┬ readable-stream@1.1.14 
  │ │     └── isarray@0.0.1 
  │ ├── negotiator@0.3.0 
  │ ├── pause@0.0.1 
  │ ├── qs@0.6.5 
  │ ├── raw-body@0.0.3 
  │ ├─┬ send@0.1.4 
  │ │ ├── mime@1.2.11 
  │ │ └── range-parser@0.0.4 
  │ └── uid2@0.0.3 
  ├─┬ debug@2.6.1
  │ └── ms@0.7.2 
  ├── mathjax@2.6.1 
  ├─┬ read@1.0.7
  │ └── mute-stream@0.0.7 
  └─┬ socket.io@1.3.3
    ├─┬ debug@2.1.0
    │ └── ms@0.6.2 
    ├─┬ engine.io@1.5.1 
    │ ├── base64id@0.1.0 
    │ ├─┬ debug@1.0.3 
    │ │ └── ms@0.6.2 
    │ ├─┬ engine.io-parser@1.2.1 
    │ │ ├── after@0.8.1 
    │ │ ├── arraybuffer.slice@0.0.6 
    │ │ ├── base64-arraybuffer@0.1.2 
    │ │ ├── blob@0.0.2 
    │ │ ├─┬ has-binary@0.1.5 
    │ │ │ └── isarray@0.0.1 
    │ │ └── utf8@2.0.0 
    │ └─┬ ws@0.5.0 
    │   ├── nan@1.4.3 
    │   ├── options@0.0.6 
    │   └── ultron@1.0.2 
    ├─┬ has-binary-data@0.1.3 
    │ └── isarray@0.0.1 
    ├─┬ socket.io-adapter@0.3.1 
    │ ├─┬ debug@1.0.2 
    │ │ └── ms@0.6.2 
    │ ├── object-keys@1.0.1 
    │ └─┬ socket.io-parser@2.2.2 
    │   ├── debug@0.7.4 
    │   └── isarray@0.0.1 
    ├─┬ socket.io-client@1.3.3 
    │ ├── backo2@1.0.2 
    │ ├── component-bind@1.0.0 
    │ ├── component-emitter@1.1.2 
    │ ├── debug@0.7.4 
    │ ├─┬ engine.io-client@1.5.1 
    │ │ ├── component-inherit@0.0.3 
    │ │ ├─┬ debug@1.0.4 
    │ │ │ └── ms@0.6.2 
    │ │ ├─┬ has-cors@1.0.3 
    │ │ │ └── global@2.0.1 
    │ │ ├── parsejson@0.0.1 
    │ │ ├── parseqs@0.0.2 
    │ │ ├── parseuri@0.0.4 
    │ │ ├─┬ ws@0.4.31 
    │ │ │ ├── commander@0.6.1 
    │ │ │ ├── nan@0.3.2 
    │ │ │ └── tinycolor@0.0.1 
    │ │ └── xmlhttprequest@1.5.0 
    │ ├─┬ has-binary@0.1.6 
    │ │ └── isarray@0.0.1 
    │ ├── indexof@0.0.1 
    │ ├── object-component@0.0.3 
    │ ├─┬ parseuri@0.0.2 
    │ │ └─┬ better-assert@1.0.2 
    │ │   └── callsite@1.0.0 
    │ └── to-array@0.1.3 
    └─┬ socket.io-parser@2.2.3 
      ├── benchmark@1.0.0 
      ├── debug@0.7.4 
      ├── isarray@0.0.1 
      └── json3@3.2.6 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/nodeppt/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

![image](https://cloud.githubusercontent.com/assets/1536470/22960796/bf02c332-f37b-11e6-9e34-3479fe9f6075.png)

**Comment by myzhan** [comment]
遇到同样的问题，nodeppt server启动的时候会卡住..
环境：
Linux系统
$ node -v               
v6.9.2
$ npm -v
3.10.9

**Comment by shaneing** [comment]
同样的问题

**Comment by jdpxiaoming** [comment]
+1,请求支援

**Comment by zp29** [comment]
哇，你们还有提示，我们的完全就卡那，不动了

**Comment by yinkaihui** [comment]
带上 -H 参数，nodeppt start -H 127.0.0.1。再去访问127.0.0.1:8080看看

**Comment by yinkaihui** [comment]
我出现的情况是 nodeppt start 命令之后，打开127.0.0.1:8080页面是can't reach。通过以上方法就可以了。

**Comment by ksky521** [comment]
没有Ubuntu系统的电脑，/(ㄒoㄒ)/~~

**Comment by asafei** [comment]
@yinkaihui 
very good，你的两个方式都是都行的，谢谢。

**Comment by kavinbright** [comment]
good man, I'm come from China Hubei, Just niubi
