### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by tomatojacky** [ksky521/nodeppt#156]
⠸ Installing nan@^2.3.0RequestError: socket hang up (req "error"), GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":21,"closeSocketCount":20,"errorSocketCount":0,"timeoutSocketCount":15,"requestCount":150,"freeSockets":{},"sockets":{"github.com:443:::::::true":1},"requests":{}})
headers: {}
    at createHangUpError (_http_client.js:210:15)
    at TLSSocket.socketCloseListener (_http_client.js:242:23)
    at emitOne (events.js:83:20)
    at TLSSocket.emit (events.js:170:7)
    at TCP._onclose (net.js:470:12)
npminstall version: 2.10.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/tomatoboy/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org -g nodeppt

**Comment by ksky521** [comment]
试下2.0
