### ISSUE TITLE
为啥nodePPT的图片地址是以 / 开头的

### ISSUE THREAD

**Issue by istommao** [ksky521/nodeppt#163]
正常的markdown图片都是 以 ./ 开头的

发现 nodePPT 没有 点 而是 直接 ／ 开头 这样 在 github 中显示不了图片
而且这也 不符合 markdown语法啊

**markdown 写法**

![image](https://cloud.githubusercontent.com/assets/5070879/24283684/38824f64-10a2-11e7-9ac7-6481d05467e2.png)

**nodePPT的写法**

![image](https://cloud.githubusercontent.com/assets/5070879/24283674/2760451a-10a2-11e7-8efe-ccc4cafcb218.png)

**Comment by ksky521** [comment]
新版本用 webpack 打包，解决了这个问题

**Comment by jinsanity07git** [comment]
新版中这个图片路径的问题 好像依然存在
会报错
```
 ERROR  Failed to compile with 0 errors
