### ISSUE TITLE
chrome无法正确导出pdf

### ISSUE THREAD

**Issue by JavanLee** [ksky521/nodeppt#164]
环境
- nodeppt版本`1.4.2`
- macos 10.12.2 && chrome  57.0.2987.133 (64-bit)
- or win7 && chrome 56.0.2924.87 (64-bit)

问题描述
1.未标明页码，且添加`?print=1`，黑屏。如`http://qdemo.sinaapp.com/?print=1`
2.标明页码，添加`?print=1`，打印只出现第一页。如`http://qdemo.sinaapp.com/#1?print=1`or`http://qdemo.sinaapp.com/#1000?print=1`

**Comment by ishenyi** [comment]
I have the same question
