### ISSUE TITLE
Fedora 下启动不了

### ISSUE THREAD

**Issue by shaneing** [ksky521/nodeppt#168]
我用的是 Fedora 发行版的 Linux 系统，安装：

```
npm install -g nodeppt
```

然后：

```
nodeppt start -d ./
```

没有任何动静，卡住一样，但是安装的是时候有警告：

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/nodeppt/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

记得以前能用的，现在不行了。

**Comment by popwin** [comment]
###遇到了同样的问题，请问时候解决

**Comment by popwin** [comment]
###遇到了同样的问题，请问是否已经解决

**Comment by shaneing** [comment]
去下载以前的版本

popwin <notifications@github.com>于2017年6月17日 周六17:30写道：

**Comment by myzhan** [comment]
发现默认没有 listen 在 0.0.0.0 上，你可以试试这样启动 nodeppt start -p 8080 -H 127.0.0.1，然后访问 127.0.0.0:8080

**Comment by zp29** [comment]
deepin 也出现同样的问题
`nodeppt start`
没有任何反响

**Comment by ksky521** [comment]
这应该个Ubuntu的是一个问题，我默认绑定在了0.0.0.0，加个-H 127.0.0.1就解决了

**Comment by zp29** [comment]
我的已经解决了，使用linux的时候，输入`nodeppt start -p 2929 -H 127.0.0.1`，直接进入127.0.0.1：2929就可以了，不会像windows那样有提示信息～.～

**Comment by ksky521** [comment]
@zp29 👍
