### ISSUE TITLE
nodeppt generate 网页没有 css 样式

### ISSUE THREAD

**Issue by hijkzzz** [ksky521/nodeppt#172]
什么样式效果都没有
排版也是乱的
在 Windows 下和 macOS下 都是这样

**Comment by ksky521** [comment]
详细说下用了什么命令

**Comment by CharlieUofT** [comment]
请使用 -a Flag输出css和js

**Comment by alyoull** [comment]
为什么我的sublime text 3不能在浏览器显示完成的DEMO，上面说的使用 -a Flag输出css和js小白看不懂，麻烦解释一下呗~~ @hijkzzz @ksky521 @CharlieUofT @utensil @jsw0528

**Comment by ksky521** [comment]
就是-a是全部输出的意思
