### ISSUE TITLE
最近更新的这个版本不能用了...

### ISSUE THREAD

**Issue by ZizhuoWang** [ksky521/nodeppt#175]
![](https://raw.githubusercontent.com/ZizhuoWang/ImageBed/network/nodeppt.png)
> 就是这样

**Comment by ZizhuoWang** [comment]
nodejs是6.11版的，事实上我也试过8.x版的也不行:joy:

**Comment by zuohuadong** [comment]
同样的问题

**Comment by zuohuadong** [comment]
使用上一个版本吧  
```
npm install nodeppt@1.4.3 -g
```

**Comment by ksky521** [comment]
我看下~

**Comment by ksky521** [comment]
不好意思，nodePPT名字改的时候，文件名漏掉了，已经在1.4.5新版本修复

**Comment by ZizhuoWang** [comment]
谢谢大大:smile:
