### ISSUE TITLE
0.8 版本不生成二维码了??

### ISSUE THREAD

**Issue by youxiachai** [ksky521/nodePPT#18]
`nodeppt start -d ./sharedppt -c socket`

打开页面..为什么现在按Q 都不显示二维码了..

**Comment by sofei** [comment]
不显示二维码，后台报错 
8090/js/nodeppt.control.socket.js:196
Uncaught ReferenceError: io is not defined
if (io && io.connect) {
                //已经存在
                Socket.connect();
            } else {
                MixJS.loadJS(socketIOURL, function() {
                    Socket.connect();
                });
            }

**Comment by sofei** [comment]
用1.0版本用start -w 可以，但是手机操控特别卡，请问-w 和 -c socket有什么区别

**Comment by ksky521** [comment]
watch是使用socket来做的

**Comment by ksky521** [comment]
io报错问题，已经解决，更新下版本即可
