### ISSUE TITLE
请教nodeppt generate -a生成时如何修改mathjax的设置

### ISSUE THREAD

**Issue by murongxixi** [ksky521/nodeppt#180]
我自己修改了node_modules\mathjax\config\default.js中的一些设置，但是发现用nodeppt generate -a生成的html里没有改变，依然还是
MathJax.Hub.Config({
  config: ["TeX-AMS-MML_HTMLorMML.js"],
  tex2jax: {inlineMath: [['\\(','\\)']]}});
  //['$','$'], 避免货币价格冲突

**Comment by ksky521** [comment]
这个没办法修改，只能手都维护了
