### ISSUE TITLE
怎么把标题放在最上面，居左

### ISSUE THREAD

**Issue by panlei7** [ksky521/nodeppt#181]
文本图片什么的都在中间，以前做ppt时习惯在最上面加标题，这个要怎么弄？

还有如果用<div class="columns2">
两张图片宽度都很窄，只占屏幕中间一点点，四周还有大块的空间，这个需要怎么改？

**Comment by murongxixi** [comment]
改nodeppt.css里的配置

**Comment by ksky521** [comment]
定制化的需求可以写个css，然后引入进来
