### ISSUE TITLE
Can not print to PDF

### ISSUE THREAD

**Issue by fan3cn** [ksky521/nodeppt#190]
type `http://js8.in/nodeppt/?print=1` in the browser, the screen gets nothing but darkness.
在浏览器里输入`http://js8.in/nodeppt/?print=1`之后黑屏，不能打印成pdf文件

**Comment by GitHubJiKe** [comment]
you should try to do this  on your localhost.
for example: localhost://8080/**your-file-path**/your-file-name.md?print=1
it will work .

**Comment by ksky521** [comment]
新版本不用 print 参数了，直接浏览器打印即可
