### ISSUE TITLE
怎样在vps服务器上长期开启nodeppt服务啊？

### ISSUE THREAD

**Issue by LiuHao713** [ksky521/nodeppt#195]
我用命令nodeppt start -p 端口   这样是开启服务了。  用浏览器联网就能看见PPT演示了。但是ctrl + c 就没了。我想的是   在断开与服务器的链接之后   也是可用的，怎么做啊？

**Comment by cheft** [comment]
根据源码显示，在同目录里安装 nodeppt
`npm i nodeppt`

创建 app.js
```js
var nodeppt = require('nodeppt')
nodeppt.start({
  port: 8080,
  host: '127.0.0.1',
  dir: __dirname + '/ppt'
})
```

ppt 的 md 文件放在 同级 ppt 目录下，接下来就按 node 项目后台启动 OK 了，用 pm2 也可以的。
