### ISSUE TITLE
在项目根目录重复运行 `nodeppt generate ./ -a` 会在publish文件夹又生成一个publish

### ISSUE THREAD

**Issue by minororange** [ksky521/nodeppt#203]
犹如递归一样，`publish` 文件夹会不断生成 `publish` 

每一个 `publish` 文件夹的目录结构都是一样的

![image](https://user-images.githubusercontent.com/25793112/42799651-33ad31c2-89cb-11e8-9cd6-fd18c74a66a2.png)

**Comment by mapann** [comment]
遇到同样的问题，作者好像给出了解决办法，但是没看明白是怎么回事。把要修改的文件替换过来，直接不生成html了
