### ISSUE TITLE
magic子页面切换Bug

### ISSUE THREAD

**Issue by TaroXin** [ksky521/nodeppt#207]
在`slide`中存在三个子页面，来回切换会产生未回到上一个子页面而回到了上一个`slide`的情况

### 重现步骤
最后一个 `slide` 中，放入三个子页面，点击跳转按钮，到预览第三个子页面时候，再次点击一次右方向键，页面不会切换，然后点击左方向键向前切换，到子页面二时，再次点击左方向键，没有回到子页面一，而是回到了上一个`slide`

**Comment by ksky521** [comment]
不在支持 magic，现在2.0的动效更多哦~
