### ISSUE TITLE
slider image不支持本地图片？

### ISSUE THREAD

**Issue by githoniel** [ksky521/nodeppt#219]
* Operating System: Win 10.0.17763.316
* Node Version: v10.15.0
* nodeppt Version: 2.1.1

RT，本地图片并不会被webpack处理, dev模式
```
![Code](./intro/html.png) 

      ==> http://172.20.25.22:8080/img/html.621b855d.png

<slide class="bg-black-blue fullscreen aligncenter" image="./intro/title.jpg">

      ===> http://172.20.25.22:8080/./intro/title.jpg

```

老版本的方法设置`slider`的style background也无效

**Comment by ksky521** [comment]
需要放到public文件夹下面，readme里面有介绍，还可以使用nodeppt.config设置路径

**Comment by wanghaisheng** [comment]
<slide class="bg-apple aligncenter" image="public/hissystems.png" >
@ksky521  图片放进去仍然不显示

**Comment by Young0510** [comment]
有人解决了吗

**Comment by anshilin77** [comment]
> ```
> <slide class="bg-apple aligncenter" image="public/hissystems.png" >
> <slide class="bg-apple aligncenter" image="./public/hissystems.png" >
> ```
> 
> @ksky521 图片放进去仍然不显示

放入public的资源直接可以访问，不需要在url里写入public

**Comment by Givemesomelove** [comment]
> 需要放到public文件夹下面，readme里面有介绍，还可以使用nodeppt.config设置路径

放入public的资源可直接访问，意味着你不需要在url里加入public前缀
