### ISSUE TITLE
prism的.number样式表冲突

### ISSUE THREAD

**Issue by lgc653** [ksky521/nodeppt#220]
* Operating System:win10
* Node Version:10
* nodeppt Version:2.1.1

prism的.number样式表冲突

**Comment by ksky521** [comment]
能具体点吗？是跟你的自定义样式冲突还是跟其他样式

**Comment by lgc653** [comment]
是这样的，prism高亮代码，如果代码里面有数字，prism会给他加上number的class，例如：
`<span class="token number">6</span>`
但是你的主css里面也有number的class定义，尤其是有display:flex，这样会导致显示异常
