### ISSUE TITLE
如何找到与fa-film类似的所有图标

### ISSUE THREAD

**Issue by wanghaisheng** [ksky521/nodeppt#226]
| Executable | Version |
| ---: | :--- |
| `node --version` | VERSION |
| `npm --version`  | VERSION |
| `nodeppt -v` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

:fa-users
fa-film
与之类似的是在哪里找来着

**Comment by wanghaisheng** [comment]
除了这个文件里的以外，https://github.com/webslides/WebSlides/blob/9a2dfe0e5263d5da0a1763b67b48f4037977a35a/static/css/svg-icons.css

**Comment by ksky521** [comment]
可以自己添加对应的 css
