### ISSUE TITLE
code里面嵌套图片

### ISSUE THREAD

**Issue by wanghaisheng** [ksky521/nodeppt#228]
| Executable | Version |
| ---: | :--- |
| `node --version` | VERSION |
| `npm --version`  | VERSION |
| `nodeppt -v` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

```
# 第四步、修改配置文件
# appsettings.json文件配置说明（数据库配置，权限配置，表映射配置）
```
但要写成这样图片就无法正常显示
```
# 第四步、修改配置文件
# appsettings.json文件配置说明（数据库配置，权限配置，表映射配置）
!![figure](https://raw.githubusercontent.com/liaozb/APIJSON.NET/master/APIJSON.NET/1.png .aligncenter)

```

**Comment by hqzh** [comment]
我也跟提一个,build图片指向的public本地文件会打包过去,但是url链接本地文件不会,
