### ISSUE TITLE
请问可以导出成为离线HTML文件吗

### ISSUE THREAD

**Issue by congzhaoyang** [ksky521/nodeppt#232]
有时开会可能会把大家PPT放在一个人电脑里面，但这台电脑可能并不具备node这些环境，所以可以生成离线的HTML文件吗？在别人的电脑上直接用chrome打开那种

**Comment by ksky521** [comment]
可以

**Comment by congzhaoyang** [comment]
请问怎样操作呀，在文档中没有找到解决这个问题的办法。

**Comment by congzhaoyang** [comment]
@ksky521
