### ISSUE TITLE
PPT列表页面功能

### ISSUE THREAD

**Issue by HypnosNova** [ksky521/nodeppt#241]
| Executable | Version |
| ---: | :--- |
| `node --version` | 10.15.1|
| `npm --version`  | 6.4.1|
| `nodeppt -v` | 2.1.5|

| OS | Version |
| --- | --- |
| win| 10|

我记得以前版本是支持有个页面是个列表，显示文件夹里所有的md文件，这样可以选择某个ppt，不需要每次敲命令行切换ppt。现在这个功能是移除了吗，还是需要什么命令

**Comment by Young0510** [comment]
应该是移除了。这个ppt有个编辑器就再好不过了了

**Comment by ksky521** [comment]
功能移除了

**Comment by JimmyLv** [comment]
那请问如何同时为整个目录下所有文件生成HTML文件呢？
