### ISSUE TITLE
代码块过高的时候，有属性设置最大高度吗？

### ISSUE THREAD

**Issue by linxiaowu66** [ksky521/nodeppt#243]
不是issue，是一个Question。所以不需要提供这些环境变量。

| Executable | Version |
| ---: | :--- |
| `node --version` | VERSION |
| `npm --version`  | VERSION |
| `nodeppt -v` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by ksky521** [comment]
可以设置页面的边距，让页面整体变大

**Comment by linxiaowu66** [comment]
@ksky521   再大也不行的吧 ，如果需要代码块滚动起来呢？

**Comment by ksky521** [comment]
@linxiaowu66 你可以自己添加 css 文件来解决这个问题；不建议有滚动条，导出来实际也看不到，展现效果也不好
