### ISSUE TITLE
请问怎样导出成为离线HTML文件呀？

### ISSUE THREAD

**Issue by congzhaoyang** [ksky521/nodeppt#248]
如题

**Comment by 2017rainman** [comment]
使用``` build ```命令就可以啊
```
nodeppt build your-slides.md
```
然后就可以在你的/home目录下得到dist文件夹，里面就有相应的your-slides.html

**Comment by congzhaoyang** [comment]
> 使用`build`命令就可以啊
> 
> ```
> nodeppt build your-slides.md
> ```
> 
> 然后就可以在你的/home目录下得到dist文件夹，里面就有相应的your-slides.html

原来是这样，感谢感谢

**Comment by chp175361** [comment]
怎么导出成为pdf文件呢？
