### ISSUE TITLE
build以后，echarts图无法显示

### ISSUE THREAD

**Issue by sagaidealsee** [ksky521/nodeppt#252]
mac系统，新装的nodeppt 2.0版本，效果很赞！
其它功能正常使用，但echart等几个图，build后不能显示
请帮助下，非常感谢！

| Executable | Version |
| ---: | :--- |
| `node --version` | VERSION |
| `npm --version`  | VERSION |
| `nodeppt -v` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by coderX86** [comment]
说实话我也于到了这样的问题   自己先看一下源码  看能不能解决  如果不能解决再说

**Comment by Bai-le-tian** [comment]
同样的问题，想插入echarts，但按照文档的说明并没有显示，有没有成功的示例可以借鉴一下呀？

**Comment by ksky521** [comment]
看下site目录下面的md的写法，对比下自己的写法对不对

**Comment by coderX86** [comment]
我直接克隆仓库到本地的，`build`的是`site`里面的`index/md`以及`echarts.md`这两个文件`build`之后都不能展示echarts插件

**Comment by sagaidealsee** [comment]
已经安排我们的程序员解决了，还有table的其它样式，打包成单独的html本地文件等功能，晚些完善了上传上来

**Comment by coderX86** [comment]
之前我也需要用到单文件打包的功能，我自己做了一个python脚本来转

毕竟对node不熟 ，有官方的当然不错了
