### ISSUE TITLE
echarts插入不显示

### ISSUE THREAD

**Issue by Bai-le-tian** [ksky521/nodeppt#255]
想插入echarts，但按照文档的说明并没有显示，有没有成功的示例可以借鉴一下呀？

| Executable | Version |
| ---: | :--- |
| `node --version` | VERSION |
| `npm --version`  | VERSION |
| `nodeppt -v` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by ksky521** [comment]
看下site里面的源码

**Comment by martian-yan** [comment]
我的echarts和mermaid在serve的时候可以显示，但是build之后的html里不显示，site里面的demo也一样。

| Executable | version |
|-----------------:|:-----------:|
| node --version | v10.13.0 |
| npm --version | 6.9.0 |
| nodeppt -v       | 2.1.5 |
| Linux               | 4.19.62-1-MANJARO |

**Comment by martian-yan** [comment]
好像是个小问题，我直接在build的html里面把echarts和mermaid的引用地址前面加上`http:` 就好了。

```plain
//cdn.staticfile.org/mermaid/8.0.0/mermaid.min.js
//cdn.staticfile.org/echarts/4.1.0-release/echarts.min.js
```

前面加上`http:`

**Comment by martian-yan** [comment]
serve的时候浏览器是用的http协议，所以链接可以打开，build之后变成了用file://打开的本地html文件，省略http的链接就打不开了

**Comment by Bai-le-tian** [comment]
build的的时候报错了，好像是插件不能识别？重装了一下还是同样的报错，麻烦帮忙看下

`(base) C:\Users\Administrator\Desktop\demo>nodeppt build demo.md
 INFO  Build ...


 ERROR  Failed to compile with 1 errors                                                                      10:28:57 AM

  Error: Child compilation failed:
  Module build failed (from C:/Users/Administrator/AppData/Roaming/npm/node_modules/nodeppt/node_modules/nodeppt-parser/  index.js):
  TypeError: Cannot read property 'plugins' of undefined

  - yaml-parser.js:5 getSettings
    [npm]/[nodeppt]/[nodeppt-parser]/lib/yaml-parser.js:5:18


  - TypeError: Cannot read property 'plugins' of undefined

  - compiler.js:141 childCompiler.runAsChild
    [npm]/[nodeppt]/[html-webpack-plugin]/lib/compiler.js:141:18

  - Compiler.js:306 compile
    [npm]/[nodeppt]/[webpack]/lib/Compiler.js:306:11

  - Compiler.js:630 hooks.afterCompile.callAsync.err
    [npm]/[nodeppt]/[webpack]/lib/Compiler.js:630:14


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [npm]/[nodeppt]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:627 compilation.seal.err
    [npm]/[nodeppt]/[webpack]/lib/Compiler.js:627:30


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [npm]/[nodeppt]/[tapable]/lib/Hook.js:154:20

  - Compilation.js:1325 hooks.optimizeAssets.callAsync.err
    [npm]/[nodeppt]/[webpack]/lib/Compilation.js:1325:35


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [npm]/[nodeppt]/[tapable]/lib/Hook.js:154:20

  - Compilation.js:1316 hooks.optimizeChunkAssets.callAsync.err
    [npm]/[nodeppt]/[webpack]/lib/Compilation.js:1316:32


  - index.js:321 taskRunner.run
    [npm]/[nodeppt]/[terser-webpack-plugin]/dist/index.js:321:9

  - TaskRunner.js:48 TaskRunner.run
    [npm]/[nodeppt]/[terser-webpack-plugin]/dist/TaskRunner.js:48:7

  - index.js:227 TerserPlugin.optimizeFn
    [npm]/[nodeppt]/[terser-webpack-plugin]/dist/index.js:227:18`

**Comment by Bai-le-tian** [comment]
感谢  @martian-yan  @ksky521 ，echarts终于可以显示了哈哈
