### ISSUE TITLE
安裝nodeppt失敗，可能是node-sass 無法built?

### ISSUE THREAD

**Issue by afenc** [ksky521/nodeppt#256]
| `node --version` | v12.6.0|
| `npm --version`  | 6.9.0|
| `nodeppt -v` | 2.1.5|

| OS | Version |
| macOS Sierra | 10.14.5 |

錯誤訊息如下，請問該如何解決？

gyp verb get node dir target node version installed: 12.6.0
gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/nodeppt/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nodeppt/node_modules/node-sass/build'
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.6.0/bin/node" "/usr/local/lib/node_modules/nodeppt/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/nodeppt/node_modules/node-sass
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/nodeppt/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by afenc** [comment]
降node至10.16得解。

**Comment by InterfaceBoy** [comment]
我的节点为10.13还是报错
