### ISSUE TITLE
怎么给`slide`设置背景为本地图片

### ISSUE THREAD

**Issue by coderX86** [ksky521/nodeppt#257]
每一个`slide`的背景图片都只能设置为在线的图片么，能不能使用本地图片，我试了一下本地图片，不论是相对，还是绝对路径都不能正常显示，但是`!![](img path)`这种基本的markdown插入的图片还是能显示的

**Comment by wastee** [comment]
奇怪。我是可以的
`<slide image="/xxx.png .right-bottom">
`
放在public文件夹里

**Comment by ksky521** [comment]
看下示例，是放到 public 文件夹的

**Comment by coderX86** [comment]
嗯   好的
