### ISSUE TITLE
不支持翻页笔

### ISSUE THREAD

**Issue by ouyuran** [ksky521/nodeppt#259]
貌似翻页笔不能使用啊
----------------------------------
更新：
经测试，在官方演示页面中，方向键ArrowUp和ArrowDown不能使用。Chrome最新版本。
翻页笔发送的事件根据型号不同，有发送ArrowUp和ArrowDown的，也有发送PageUp和PageDown的。
而实际我使用的翻页笔发送的是ArrowUp/ArrowDown，所以表现为翻页笔不能使用，其实方向键上下也不可用。
另外，常用的还有黑屏键，建议支持。

| Executable | Version |
| ---: | :--- |
| `node --version` | VERSION |
| `npm --version`  | VERSION |
| `nodeppt -v` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by coderX86** [comment]
可以弯道超测，使用无线鼠标

**Comment by ksky521** [comment]
目前是判断横屏还是竖屏，然后选择使用 arrowUp 还是 arrowLeft 的

**Comment by ouyuran** [comment]
那这样翻页笔就支持不了了，而且跟power point行为也不一致吧
