### ISSUE TITLE
如何创建多个md 文件

### ISSUE THREAD

**Issue by asvencoop** [ksky521/nodeppt#262]
我想手动新建两个slide.md 文件。 
但是我通过 nodeppt serve 命令只能预览一个md 文件内容，如何通过 nodeppt serve 同时预览两个文件呢？ 

| Executable | Version |
| ---: | :--- |
| `node --version` | 10.16|
| `npm --version`  | 6.9|
| `nodeppt -v` | lastest|

| OS | Version |
| --- | --- |
| Windows 10 | 1607 |

-->

**Comment by coderX86** [comment]
你可以 nodeppt serve 两次啊  他会自动占用不同的端口的

**Comment by asvencoop** [comment]
@coderX86 两个不同的端口，我还是无法在同一个页面上切换page。我想能够实现https://nodeppt.js.org/#slide=7 这样后面带有slide=7 的分页。请问你知道如何做到吗？

**Comment by coderX86** [comment]
@asvencoop  那你为什么不把内容写道一个文件里面

**Comment by asvencoop** [comment]
@coderX86 我的所有md 文件是在一个目录下，但是我不知道启动serve 之后，怎么让他们通过 https://nodeppt.js.org/#slide=7 这样的方式串联起来

**Comment by coderX86** [comment]
你可以采用将所有的md都serve出来，然后使用iframe标签串联起来，当一个播放完毕的时候，切换iframe的src为下一个的页面的地址

**Comment by asvencoop** [comment]
@coderX86  嗯，这样可以。不过nodeppt的官网不是这样做的，它在每个section 标签上都有一个唯一的id,我想这是用某个 我错过了的 nodeppt 的api 实现的

**Comment by coderX86** [comment]
嗯，他们用的是前端路由的方式，控制页面的切换    当然你也可以这样做，不过如果你想使用iframe 的同时使用前端路由的话，那么你就不得不面临 js跨域的问题   这个搞起来比较麻烦   我不知道怎么跨域操作

**Comment by ksky521** [comment]
没必要这么做啊，你不可能同时写俩 md 文件啊

**Comment by asvencoop** [comment]
@ksky521 我想在npm serve 之后预览第二张md文件，以及预览串联起来的效果。

**Comment by kekemao00** [comment]
@asvencoop 我想你是需要把一个 .md 文件拆成单页的幻灯片内容,  README 有写:  [`<slide>`  语法](https://github.com/ksky521/nodeppt#slide-%E8%AF%AD%E6%B3%95)

**Comment by Eve-Sama** [comment]
请问只能有一个slide.md吗? 我可以不可以是slide-01.md, slide-02.md呢? 因为当一个md当中内容太多的时候, 其实查找起来比较困难. 可否支持一个入口md, 剩余的页数都分散在不同的md当中呢?
