### ISSUE TITLE
mac安装错误

### ISSUE THREAD

**Issue by jllin90** [ksky521/nodeppt#263]
`npm install -g nodeppt`. 错误提示：

../src/create_string.cpp:17:25: error: no matching constructor for
      initialization of 'v8::String::Utf8Value'
  v8::String::Utf8Value string(value);

版本如下，谢谢。

| Executable | Version |
| ---: | :--- |
| `node --version` | v12.0.0 |
| `npm --version`  | 6.9.0 |
| `nodeppt -v` | VERSION |

| macOS Sierra | 10.14.5  |
| --- | --- |
| NAME | VERSION |

**Comment by Rosso6** [comment]
同安装报错，谢谢帮助。

![image](https://user-images.githubusercontent.com/22437452/62989416-674e8f00-be7a-11e9-978a-d4e0ea3ef3bb.png)

**Comment by Rosso6** [comment]
@jllin90 fixed it by downgrading node to v11 

`npm install -g node@11.10.0`

**Comment by hiberabyss** [comment]
Has same problem, could be fixed via suggestion from @Rosso6 .

**Comment by jllin90** [comment]
@Rosso6 感谢回复。安装没问题，但是显示`-bash: nodeppt: command not found`.

**Comment by Rosso6** [comment]
> @Rosso6 感谢回复。安装没问题，但是显示`-bash: nodeppt: command not found`.

命令如果不能使用应该还是没成功。要不gitclone下来本地build下试试

**Comment by jllin90** [comment]
> > @Rosso6 感谢回复。安装没问题，但是显示`-bash: nodeppt: command not found`.
> 
> 命令如果不能使用应该还是没成功。要不gitclone下来本地build下试试

请问，本地build？`git clone`了repo， 然后
```
nodeppt new slide.md
>> -bash: nodeppt: command not found 
```

**Comment by Pluckypan** [comment]
官方给出的解决方案：
1.  mkdir ~/.npm-global
2.  npm config set prefix '~/.npm-global'
3.  export PATH=~/.npm-global/bin:$PATH

**Comment by jllin90** [comment]
@Pluckypan 已解决，谢谢。
