### ISSUE TITLE
大哥，分享一下demo的md文件啊，光看文档完全看不懂啊

### ISSUE THREAD

**Issue by omitchen** [ksky521/nodeppt#269]
| Executable | Version |
| ---: | :--- |
| `node --version` | VERSION |
| `npm --version`  | VERSION |
| `nodeppt -v` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

https://nodeppt.js.org/#slide=4
这个demo的md可以分享一下吗

**Comment by cq674350529** [comment]
@omitchen Maybe you can refer to this issue #251 . In short, all the related files lie here: https://github.com/ksky521/nodeppt/tree/master/site
