### ISSUE TITLE
全局安装nodeppt报权限错误

### ISSUE THREAD

**Issue by lsjing** [ksky521/nodeppt#277]
| Executable | Version |
| ---: | :--- |
| `node --version` | v12.13.0 |
| `npm --version`  | 6.12.0 |
| `nodeppt -v` | xxx |
| Centos 7(uname -r) | 3.10.0-514.26.2.el7.x86_64 |

Unable to save binary /root/node-v12.13.0-linux-x64/lib/node_modules/nodeppt/node_modules/node-sass/vendor/linux-x64-72 : Error: EACCES: permission denied, mkdir '/root/node-v12.13.0-linux-x64/lib/node_modules/nodeppt/node_modules/node-sass/vendor'

**Comment by ksky521** [comment]
等有时间把node-sass干掉，这个编译经常出问题。。。sad~

**Comment by ksky521** [comment]
使用新版，去掉 node-sass 了
