### ISSUE TITLE
当在浏览器里直接打开index.html时，打开速度会非常慢

### ISSUE THREAD

**Issue by delphidoc** [ksky521/nodeppt#286]
检查发现是下面这几行代码引起来的
  <‘link rel="stylesheet" href="//cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css" />
  <‘link rel="stylesheet" href="//cdn.staticfile.org/prism/1.15.0/themes/prism.min.css" />
  <‘link rel="stylesheet" href="//cdn.staticfile.org/KaTeX/0.10.0-rc.1/katex.min.css" />
  <‘link rel="stylesheet" href="//cdn.staticfile.org/KaTeX/0.5.1/katex.min.css" />

 <script src="//cdn.staticfile.org/echarts/4.1.0-release/echarts.min.js"></script>
 <script src="//cdn.staticfile.org/mermaid/8.0.0/mermaid.min.js"></script>

只要把文件中所有//开头的都替换成http://就直接秒开了。

**Comment by delphidoc** [comment]
还有那三行link的
<link rel="stylesheet" href="//cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdn.staticfile.org/prism/1.15.0/themes/prism.min.css">
    <link rel="stylesheet" href="//cdn.staticfile.org/KaTeX/0.10.0-rc.1/katex.min.css">

**Comment by ksky521** [comment]
// 是通用协议，https 的页面会使用 https 的资源，如果 https 的页面使用 http 的资源，chrome 会报错

**Comment by delphidoc** [comment]
我是在本地以文件方式打开测试的

**Comment by delphidoc** [comment]
我是在本地以文件方式打开测试的

> // 是通用协议，https 的页面会使用 https 的资源，如果 https 的页面使用 http 的资源，chrome 会报错

我是在本地以文件方式打开测试的
