### ISSUE TITLE
Support mermaid State Diagram

### ISSUE THREAD

**Issue by C0MM4ND** [ksky521/nodeppt#287]
| Executable | Version |
| ---: | :--- |
| `node --version` | v14.0.0 |
| `npm --version`  | 6.14.4 |
| `nodeppt -v` | 2.2.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 18.04 |

https://mermaid-js.github.io/mermaid/#/stateDiagram
![image](https://user-images.githubusercontent.com/12538215/80273414-69086c00-8704-11ea-8f0c-be99e92be199.png)

**Comment by ksky521** [comment]
在2.2.2版本我升级mermaid到8.5.2，是支持了的，参考：https://github.com/ksky521/nodeppt/blob/master/site/mermaid.md
