### ISSUE TITLE
如何让写好的ppt滚动播放/自动播放/连续播放？

### ISSUE THREAD

**Issue by alasaga** [ksky521/nodeppt#288]
| `node --version` | 10.16.0 |
| `npm --version`  | 6.9.0 |
| `nodeppt -v` | 2.1.5 |
| macOS Sierra | 10.12.3 |

Hi，Nodeppt很赞！

想请教下，怎么让写好生成的HTML文件自动播放?
一页放完了自动到下一页播放显示，最好能设置每页自动播放的时间
谢谢！

**Comment by ksky521** [comment]
支持的，需要改 nodeppt.js 里面的 autoplay 选项

**Comment by alasaga** [comment]
谢谢! 看了下weblisdes就是autoplay这个选项，回头我在nodeppt里面试试。做ppt，直接改webslides那种html，还是没有写markdown方便。

**Comment by alasaga** [comment]
> 支持的，需要改 nodeppt.js 里面的 autoplay 选项

Hi
我似乎没找到nodeppt.js这个文件呢，在其它js文件里面也没找到这个autoplay选项。该在哪里改呢？
可否帮助加一项这个功能？谢谢！

**Comment by ksky521** [comment]
在2.2.2版本里面，md文件的yaml里面添加：

```yaml
webslideOptions:
    autoslide: 5000
```
详细配置可以参考：https://github.com/webslides/WebSlides/wiki/Core-API#options
