### ISSUE TITLE
分享个脚本，导出单个离线HTML文件，不是用build

### ISSUE THREAD

**Issue by alasaga** [ksky521/nodeppt#289]
| `node --version` | 10.16   |
| `npm --version`  | 6.9       |
| `nodeppt -v`       | 2.1.5     |
| macOS Sierra      | 10.12.3 |
[nodepptStandalone.py.zip](https://github.com/ksky521/nodeppt/files/4586214/nodepptStandalone.py.zip)

之前同事写的，先serve，然后用爬虫全部抓下来转格式，完美生成单独的HTML文件。

简单运行方式，解压，把nodepptStandalone.py放到md文件所在目录，命令行进入目录运行：
`python3 ./nodepptStandalone.py  xxxxx.md`

**Comment by ksky521** [comment]
这个没有这么麻烦。。。为啥不用 build。。

**Comment by alasaga** [comment]
谢谢，是为了当做ppt对外分享。。。之前试过直接用build，效果没问题，但build出来会有几个文件，如果通过手机或email分享出去直接播放的话稍显麻烦。
