### ISSUE TITLE
<img src="[object Module]" alt="">本地图片不显示

### ISSUE THREAD

**Issue by lindadoudou** [ksky521/nodeppt#290]
| Executable | Version |
| ---: | :--- |
| `node --version` | v13.11.0 |
| `npm --version`  | 6.14.5 |
| `nodeppt -v` | 2.2.0 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.4 |

- 本地图片放到public目录下,显示时确只有`<img src="[object Module]" alt="">`
![image](https://user-images.githubusercontent.com/13118142/83596636-b1cf0280-a597-11ea-8cf9-2ebd5c7e1813.png)

![image](https://user-images.githubusercontent.com/13118142/83596657-c0b5b500-a597-11ea-9781-7c43a603a4c7.png)

- 之前nodeppt 2.1.8时正常使用，没有这个问题，升级到2.2.0出现这个问题，可是从2.2.0退回2.1.8之后，依然不能显示本地图片

- 在网上找过资料，提示是`file-loader`和`url-loader`的`esModule`设置问题，拉取了nodeppt源码，修改了`nodeppt/packages/nodeppt-serve/config/base.js`
![image](https://user-images.githubusercontent.com/13118142/83596877-5c472580-a598-11ea-949b-9ae6b0de6d76.png)
添加`esModule: false`到options中，从源码安装，依旧不能显示

**Comment by kenspirit** [comment]
> * esModule: false

我加了这个 option 倒是可以了。

**Comment by ksky521** [comment]
发了2.2.1版本 @kenspirit @renxia

**Comment by kenspirit** [comment]
@ksky521 可以了，谢谢。
