### ISSUE TITLE
自定义插件内的函数如何执行

### ISSUE THREAD

**Issue by CXJoyce** [ksky521/nodeppt#299]
| Executable | Version |
| ---: | :--- |
| `node --version` | v12.16.3 |
| `npm --version`  | 6.14.4 |
| `nodeppt -v` | 2.2.2 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.14.6 |

文件目录结构为：
|--public
|--index.md
|--nodeppt.config.js

自定义插件，nodeppt.config.js代码如下：
```js
var md = require('markdown-it')();

module.exports = {
  // 这里的 id 必须以 markdown/posthtml开头
  // 分别对应 markdown-it和 posthtml 插件语法

  plugins: [{
    id: 'markdown-test',
    apply: () => {
      var defaultRender = md.renderer.rules.text;
      md.renderer.rules.text = function test(tokens, idx, options, env, self) {
        console.log('test');
      }
    }
  }],
}
```

运行命令 `nodeppt serve index.md`
发现plugin的test函数没有执行，请问下怎么执行test函数

**Comment by ksky521** [comment]
apply接受的第一个参数是md，不要用你require的md：
```js
apply(md){

 // md.renderer.rule
}
```

**Comment by CXJoyce** [comment]
感谢这么及时的回复，我试下，多谢啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 三水清 <notifications@github.com&gt;
发送时间: 2021年1月25日 10:53
收件人: ksky521/nodeppt <nodeppt@noreply.github.com&gt;
抄送: CXJoyce <511599323@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ksky521/nodeppt] 自定义插件内的函数如何执行 (#299)





 
apply接受的第一个参数是md，不要用你require的md：
 apply(md){  // md.renderer.rule }

**Comment by CXJoyce** [comment]
解决了，多谢多谢
