### ISSUE TITLE
加载本地图片

### ISSUE THREAD

**Issue by UMbalrog** [ksky521/nodeppt#300]
加载本地图片时，本地服务返回是 content-type： text/html 格式不对，导致本地图片出不来，可否兼容一下

| Executable | 1 |
| ---: | :--- |
| `node --version` | 1 |
| `npm --version`  | 1 |
| `nodeppt -v` | 1 |

| OS | 1 |
| --- | --- |
| NAME | 1 |

**Comment by UMbalrog** [comment]
已解决

**Comment by Eve-Sama** [comment]
已解决为什么不close?
