### ISSUE TITLE
fontawesome无法使用

### ISSUE THREAD

**Issue by turtlekey** [ksky521/nodeppt#301]
| Executable | Version |
| ---: | :--- |
| `node --version` |  v14.16.0|
| `npm --version`  | v7.7.5 |
| `nodeppt -v` | v2.2.2 |

| OS | Version |
| windows 10| 2004 |
| NAME | VERSION |

无法使用fontawesome， 除了官方demo中的`fa-github`，其他图标均无法加载成功，呈现空白。已尝试所有格式：`:fa-keyboard:`,`:~fa-keyboard:~`,`::fa-keyboard::`，均无效

**Comment by turtlekey** [comment]
已解决。
解决方式： 自行在`.md`文件中添加fontawesome的css文件，如`https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.3/css/all.min.css`，可能是版本不兼容而导致问题。
仍然存在的问题：此时会请求两个fontawesome的css文件，大神能告诉一下自带的fontawesome静态资源在哪取消吗？

**Comment by ksky521** [comment]
目前默认的是没地方取消的

**Comment by sailonthrough** [comment]
Your email is received and will be handled  as soon as possible,and this is an automatic reply,I will respond to your message  immediately when I see it.Thank you.
