### ISSUE TITLE
怎么才能在一个页面里一条一条显示

### ISSUE THREAD

**Issue by jumplee** [ksky521/nodePPT#50]
http://qdemo.sinaapp.com/#2 中的效果

readme.md 中貌似没有看到啊

@ksky521

**Comment by JackPu** [comment]
[image: 内嵌图片 1]
在后面加动画哦，

2015-02-26 9:33 GMT+08:00 lee <notifications@github.com>:

> Closed #50 <https://github.com/ksky521/nodePPT/issues/50>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ksky521/nodePPT/issues/50#event-242197066>.
>



-- 

*来自* *Jack*
