### ISSUE TITLE
Chrome 下已经禁止了字体跨域

### ISSUE THREAD

**Issue by shijinyu** [ksky521/nodePPT#52]
markdown代码样式仍然使用了跨域的http://fontscontent.useso.com/static/fonts/sourcecodepro/v4/XXX.woff，在chrome下会产生一个错误（Not Allowed），同时，该国外域名存在访问不稳定，字体下载时间比较久会导致 md下代码样式长时间得不到渲染。

**Comment by ksky521** [comment]
已经修改~ 谢谢提醒~
