### ISSUE TITLE
mac OS x 10.10.1  出现问题。env: node\r: No such file or directory

### ISSUE THREAD

**Issue by fyddaben** [ksky521/nodePPT#54]
npm -g 安装成功，
运行命令 `nodeppt start -h`,出现 
`env: node\r: No such file or directory`

##解决方法

找到`/usr/local/lib/node_modules/nodeppt/bin`,
然后`sudo vim nodeppt`,
然后`:set ff=unix`
然后`:w`保存

**Comment by ksky521** [comment]
重新发了个包~ 现在安装就可以了
