### ISSUE TITLE
请问如何设置全局的背景图片样式？

### ISSUE THREAD

**Issue by shanggqm** [ksky521/nodePPT#58]
看了文档，只知道可以对单个卡片设置背景图片：
```
[slide style="background-image:url(/img/mainBg.jpg)"]
```
不知是否支持全局的设置？
另外设置了背景图，在slide里添加宽高不大的图片，图片样式会被拉伸：
![image](https://cloud.githubusercontent.com/assets/2172641/6054327/90200f18-ad26-11e4-86bb-53485ffbc04b.png)

代码如下：
```
[slide style="background-image:url(/img/mainBg.jpg)"]
##ES5 模块化现状 --CommonJs
----
![CommonJs](/img/commonjs.png "commonJs")
```

**Comment by ksky521** [comment]
background的问题已经解决，更新最新版看下
