### ISSUE TITLE
你需要有一个高端大气上档次的介绍或者demo页至少要有一个高端大气上档次的logo

### ISSUE THREAD

**Issue by cnberg** [ksky521/nodePPT#67]
否则，在 http://div.io/digg 里面，你的图片不够高端大气上档次啊。

**Comment by ksky521** [comment]
求设计啊~哈哈

**Comment by cnberg** [comment]
你去组里找一个UE妹子设计一下啊，到时候我在divio上推广下

--------------
Yours sincerely
berg
http://cnberg.com
@cnberg
