### ISSUE TITLE
PDF printing

### ISSUE THREAD

**Issue by sebelk** [ksky521/nodePPT#71]
Hi,

I've tested the example of pdf exporting and only outputs a blank pdf.

Thanks in advance!

**Comment by ksky521** [comment]
use ctrl+p in chrome

**Comment by xujiajun** [comment]
@ksky521  你好，

我在chrome 能导出pdf，不过会出现第二张ppt全黑的情况（其他ppt均正常）。

希望得到帮助 谢谢。

**Comment by ksky521** [comment]
已知问题，现在我的做法是，将页面url加#1000，这样最后在ctrl+p，最后一张就不会黑了

**Comment by xujiajun** [comment]
@ksky521   恩。Tks

**Comment by zlowly** [comment]
这个坑好大啊，我也在这困扰了几天，差点就放弃继续使用了，直到在issues里发现这个解决方法。
如果无法修复（无论短期或永久），能否将这个临时解决方案加入readme中？

**Comment by ksky521** [comment]
这个我再看看，拖了好久了，应该搞搞了~

**Comment by Honghe** [comment]
> 已知问题，现在我的做法是，将页面url加#1000，这样最后在ctrl+p，最后一张就不会黑了
为何加`#1000`，第二张就不会变黑，好神奇

**Comment by ksky521** [comment]
改了下，使用url?print=1 然后打印吧，原因还没找出。。

**Comment by ufologist** [comment]
刚好我也碰到了这个bug, 相信很多朋友也会有如此的疑惑, 我这里小小总结下吧

1. 关于 ctrl + p 快捷键的使用
    在使用 ctrl + p 快捷键导出(打印)PPT时, 需要先点击下浏览器的地址栏(即将输入焦点放在地址栏上), 否则只会激活nodeppt 的画笔功能, 而不是触发chrome的打印功能.

2. 打印时遇到PPT某页是全黑的情况
    也就是遇到如上提到的这个bug, 可以通过在 URL 中补上?print=1 或者 #1000
    这里的 #1000 即翻页到 PPT 的某一页, 这里指定一个不存在的页码, 会强行让打印时渲染出全部页, 因此机智的绕过了这个bug

3. 打印设置
    要想导出 pdf, 还需要最后设置一下才行.
![nodeppt-print-pdf-settings](https://cloud.githubusercontent.com/assets/167221/10409509/0d87bb08-6f56-11e5-9b20-1e6399701184.png)
