### ISSUE TITLE
导出html文件放到github page出问题

### ISSUE THREAD

**Issue by luxiaojian** [ksky521/nodePPT#73]
本地html打开的样式  

![ ](http://luxiaojian.qiniudn.com/屏幕快照 2015-05-14 下午8.51.23.png)
同步到github pages后高亮消失，如下图  
![](http://luxiaojian.qiniudn.com/屏幕快照 2015-05-14 下午8.51.15.png)

**Comment by ksky521** [comment]
可能文件路径不对吧，你看看自己调整下

**Comment by Xuanwo** [comment]
可能是高亮代码的js之类的没有找到，你F12看看有没有报错的
