### ISSUE TITLE
【BUG】你给出的Demo中，如果左右箭头点击过快，黄色的云没有消失，会存在下一个slide中。

### ISSUE THREAD

**Issue by hellfiresong** [ksky521/nodePPT#74]
![snip20150517_1](https://cloud.githubusercontent.com/assets/7992020/7668745/73c1c9f2-fc7b-11e4-8c10-aa7dbd2fa94f.png)
如图所示：在你给出的默认demo的基础之上进行修改。如果快速的重复按着左箭头或者右箭头的化，到了这个黄色的云朵这个地方。黄色的云朵会仍然存在于下一个slide。由于我已经多次使用这个nodePPT这个工具，感觉效果挺不错的，反馈下，希望这款工具做得更好！

**Comment by ksky521** [comment]
这个新的demo应该解决了~
