### ISSUE TITLE
将 useso 放到本地

### ISSUE THREAD

**Issue by nimojs** [ksky521/nodePPT#76]
网速慢的情况下需要等待 useso 加载，速度太慢了。
```
@import url(http://fonts.useso.com/css?family=Source%20Code%20Pro:light,regular,semibold);
```

https://github.com/ksky521/nodePPT/blob/f5f513e730284e91bf74ab66cee5dd1d033a80a5/assets/scss/nodeppt.scss#L2

**Comment by zlowly** [comment]
是啊，最好把对互联网资源的依赖都去除掉，因为有时候演示环境不一定可以联网的。

**Comment by ksky521** [comment]
本来想使用google的，发现360有个这个，下载到本地会不会有版权问题？

**Comment by Xuanwo** [comment]
不会

**Comment by ksky521** [comment]
已经放到本地~

**Comment by Xuanwo** [comment]
参考Source Code Pro的版权声明：
https://github.com/adobe-fonts/source-code-pro/blob/master/LICENSE.txt
其中使用了SIL Open Font License (OFL)证书，要求如下：
```
enable others to participate in our projects
enable others to cater to needs for which we don't have the resources
share our wealth of knowledge and experience in the area of writing systems and pass on our tools
equip the community to meet its font needs
```

其Adobe已经授权我们可以使用此字体，谷歌和360只不过提供了字体的CDN下载
