### ISSUE TITLE
集成动态编译环境

### ISSUE THREAD

**Issue by shy2850** [ksky521/nodePPT#77]
今天上午看到这个项目，正是我想要的，但是不希望再使用一整套集成环境， 只是需要一个编译过程模块就好。 遂改动一下集成到自己的项目中 [f2e-server](https://github.com/shy2850/node-server)， 期望后续能够支持这样更纯粹的版本。

clone目录： 
https://github.com/shy2850/node-server/blob/master/nodeLib/filter/nodePPT
f2e-server中使用中间件方式引入： 
https://github.com/shy2850/node-server/blob/master/nodeLib/filter/middleware.js#L62

主要修改如下：
1. 去除 font-awesome.css 依赖.
2. 对 marked 的依赖直接使用node包依赖设置
3. 将ejs模板引擎直接替换成 underscore.template 
4. 不处理默认的静态文件依赖， 直接引用的是 http://qdemo.sinaapp.com/ 下面的远程资源 (是否可行？ 求建议)
5. 解析器只复制了最基本的部分， script 标签等处理貌似有问题， 内部的换行自动转换成 br 标签了
6. 因为 `.md` 后缀名给纯粹的markdown文件使用， 在 f2e-server中使用了 `.mdppt` 作为新的后缀名使用。

Demo 地址： http://f2e-server.com:2850/demo/ppts/demo.mdppt

**Comment by ksky521** [comment]
挺好的，marked是修改过的，所以不是走的包依赖
