### ISSUE TITLE
【BUG】保存为pdf格式有BUG

### ISSUE THREAD

**Issue by Voidly** [ksky521/nodePPT#88]
如果存在[subslide]时，保存为pdf会缺少[subslide]的页面

**Comment by ksky521** [comment]
使用?print=1呢

**Comment by Voidly** [comment]
仍然**不行**。。。

**Comment by ksky521** [comment]
使用最新版

**Comment by Voidly** [comment]
加上?print=1在浏览器端，直接C-p，保存不行，nodeppt pdf http://172.30.2.249:8080/md/mon.md\?print\=1 ccc.pdf  仍然不行。。。

**Comment by Voidly** [comment]
当前版本1.2.4 如何进行升级？
