### ISSUE TITLE
superscript tag ignored

### ISSUE THREAD

**Issue by sebelk** [ksky521/nodePPT#91]
Hi,

If I write: 

2<sup>2</sup>

is ignored at all and rendered as:

```
22
```

Any ideas?

Thanks in advance!

**Comment by sebelk** [comment]
It was somewhat about css as we can take a look at http://stephenpkane.com/what-to-do-when-html-tags-like-sub-and-sup-dont-work/

**Comment by ksky521** [comment]
fix it @1.3.1 version; enjoy it~
