### ISSUE TITLE
斜体没有实现吗？

### ISSUE THREAD

**Issue by decker502** [ksky521/nodePPT#92]
按markdown标准语法，用＊，　＿ 都无法实现斜体的效果，是没有实现吗？多谢

**Comment by Xuanwo** [comment]
请适应英文半角字符`*`
*就像这样*

**Comment by decker502** [comment]
确认是使用的半角英文字符*, 显示的效果只是粗体，没有斜体

系统：ubuntu15.04
浏览器： chrome, firefox
Node: v0.10.25

**Comment by ksky521** [comment]
已经实现；@1.3.1 version; enjoy it~
