### ISSUE TITLE
强化媒体支持，预置一些图片处理效果，预定义视频播放器等。

### ISSUE THREAD

**Issue by pinxue** [ksky521/nodePPT#94]
虽然直接操作 HTML 啥都能放，不过图片效果和视频支持还是可以强化一下。
另外参照苹果的 iBooks Author ，把 IFRAME 强化成一个 widget 插件机制就更方便，互动表单、地图、3D模型什么的都可以直接包装第三方的，如果接口一样的话，那连包装都省了。

**Comment by ksky521** [comment]
你有需求，欢迎提pull啊~
