### ISSUE TITLE
Background of a slide bad rendered in HTML

### ISSUE THREAD

**Issue by sebelk** [ksky521/nodeppt#95]
Hi,

When I set the background of a slide, let' say:

[slide style="background-image:url('/server-startup-1243091.jpg')"]

it's seen well but after is exported it's bad rendered, so I have to preppend manually a dot:

[slide style="background-image:url('./server-startup-1243091.jpg')"]

So `node generate -a` output is correct, but in this case nodeppt don't show correctly in the browser.

Thanks in advance

**Comment by ksky521** [comment]
use nodeppt 2.0
